config/routes.rb
Rails.application.routes.draw do

    resources :categories
    resources :products do
      post :assign, on: :member
    end

    resources :stores

    get 'tags/:tag', to: 'categories#index', as: :tag

    root to: 'stores#index'

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :city
  belongs_to :country

  has_many :store_products
  has_many :products, through: :store_products
  
  validates :name, :street, :number, :zipcode, :city, :country, presence: true
  validates :number, :zipcode , numericality:  { only_integer: true}
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [ :edit, :show, :update, :destroy]
  before_action :load_catalog, only: [:new, :edit, :create, :update]
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.paginate(page: params[:page],per_page: 10)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show

  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_url, notice: t(:store_saved_success) }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to stores_url, notice: t(:store_updated_success) }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    flash[:success] =  t(:store_destroyed_success)
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :street, :number, :zipcode, :city_id, :country_id)
    end

    def load_catalog
      @cities = City.all
      @countries = Country.all
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
    <%=render 'general/errors', modelo: store%>

  <div class="form-group field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', maxlength: 50,autofocus: true %>
  </div>

  <div class="field form-group">
      <%= form.label :street %>
      <%= form.text_field :street, class: 'form-control', maxlength: 50 %>
  </div>

  <div class="field form-group">
      <%= form.label :number %>
      <%= form.text_field :number, class: 'form-control numberText', maxlength: 6 %>
  </div>

  <div class="field form-group">
      <%= form.label :zipcode %>
      <%= form.text_field :zipcode, class: 'form-control numberText', maxlength: 6 %>
  </div>

  <div class="field form-group">
      <%= form.label :country_id %>
      <%= form.collection_select :country_id, @countries,:id,:name, {include_blank: true}, {class: 'form-control'} %>      
  </div>
  
  
  <div class="field form-group">
      <%= form.label :city_id %>
      <%= form.collection_select :city_id, @cities,:id,:name, {include_blank: true}, {:class=>'form-control'} %>
      
  </div>


  <div class="actions">
    <%= form.submit t('.save'), :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/stores/_no_data.html.erb
<tr class="row-line row-store">
    <td colspan="8">
	<div class="no-data">
	    <%= t :no_stores%>
	</div>
    </td>
</tr>

app/views/stores/_products.html.erb
<div class="table-responsive">
    <table class="table table-hover">
	<thead>
	    <tr>
		<th><%=t 'activerecord.attributes.product.name'%></th>
		<th><%=t 'activerecord.attributes.product.stock'%></th>
		<th></th>

		<th colspan="2"></th>
	    </tr>
	</thead>

	<tbody>
	    <%if !@store.nil?%>
		<% @store.store_products.each do |product| %>
		    <tr class="row-line row-store">
			<td><%= product.product.name %></td>
			<td><%= product.stock||0 %></td>
			<td>

			</td>
		    </tr>
		<%end%>
 
	    <%else%>
		<%=render 'products/no_data' %>
	    <%end%>
	</tbody>
    </table>

</div>

app/views/stores/_tabs.html.erb
<h1><%=t('.title',name: store.name) %></h1>
<div class="container">
    <ul class="nav nav-pills">
	<li role="presentation" class="<%=isActionActive("edit") %>"><%=link_to "General", edit_store_path(store) %></li>
	<li role="presentation" class="<%=isActionActive("show")%>"><%=link_to "Productos", store %></li>
</ul>
</div>

app/views/stores/edit.html.erb
<div class="card">
    <%= render 'tabs', store: @store %>    
    <%= render 'form', store: @store %>
</div>
<%= link_to t(:back), stores_path %>

app/views/stores/index.html.erb
<div class="card">
<h1><%= t '.title' %></h1>
<p>
    <%= link_to t('new'), new_store_path, class: 'btn btn-primary' %>
</p>
<div class="table-responsive">
    <table class="table table-hover">
	<thead>
	    <tr>
		<th><%=t 'activerecord.attributes.store.name'%></th>
		<th><%=t 'activerecord.attributes.store.country'%></th>
		<th><%=t 'activerecord.attributes.store.city'%></th>
		<th><%=t 'activerecord.attributes.store.street'%></th>
		<th><%=t 'activerecord.attributes.store.number'%></th>
		<th><%=t 'activerecord.attributes.store.zipcode'%></th>

		<th colspan="2"></th>
	    </tr>
	</thead>

	<tbody>
	    <%if !@stores.nil?%>
		    <% @stores.each do |store| %>
			<tr class="row-line row-store">
			    <td><%= link_to store.name, edit_store_path(store) %></td>
			    <td><%= store.country.name %></td>
			    <td><%= store.city.name %></td>
			    <td><%= store.street %></td>
			    <td><%= store.number %></td>
			    <td><%= store.zipcode %></td>
			    <td><%= link_to t(:edit), edit_store_path(store) %></td>
			    <td><%= link_to t(:destroy), store, method: :delete, data: { confirm: t(:are_you_sure, name: store.name) } %></td>
			</tr>
		    <%end%>
   		    <%if @stores.length==0%>
			<%=render 'no_data' %>
		    <% end %>
	    <%else%>
		    <%=render 'no_data' %>
	    <%end%>
	</tbody>
    </table>
    <%= will_paginate @stores %>
</div>
</div>

<br>

app/views/stores/new.html.erb
<div class="card">
    <h1><%=t '.title' %></h1>
    
    <%= render 'form', store: @store %>
</div>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div class="card">
    <%= render 'tabs', store: @store %>
    <%= render 'products', store: @store %>
</div>


<%= link_to 'Back', stores_path %>