config/routes.rb
Rails.application.routes.draw do

    resources :categories
    resources :products do
      post :assign, on: :member
    end

    resources :stores

    get 'tags/:tag', to: 'categories#index', as: :tag

    root to: 'stores#index'

end

app/views/general/_errors.html.erb
<% if modelo.errors.any? %>
    <div id="error_explanation">
	<h2><%= t(:errors) %> :</h2>

	<ul>
	    <% modelo.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	    <% end %>
	</ul>
    </div>
<% end %>

app/views/general/_navbar.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
	    <span class="sr-only">Toggle</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	</button>
	<a href="<%= root_url %>" class="navbar-brand">JustClick</a>
    </div>
    <div id="main_mnu" class="sidebar-collapse ">
	<ul class="nav navbar-nav sidebar-menu">
	    <li>	  <%=t(:switch) %>  <% if I18n.locale == I18n.default_locale %>
		<%= link_to "Ingles", { :locale=>'en' } %>

	    <% else %>
		<%= link_to "Spanish", { :locale=>'es' } %>

	    <%end%>
	    </li>
	    <li class="<%=isMenuActive("stores")%> "><%= link_to t('activerecord.models.store.other'),stores_url %></li>
	    <li class="<%=isMenuActive("products")%>"><%= link_to t('activerecord.models.product.other'), products_url %></li>
	    <li class="<%=isMenuActive("categories")%>"><%= link_to t('activerecord.models.category.other'),categories_path %></li>
	    
	</ul>
    </div>
</header>