config/routes.rb
Rails.application.routes.draw do

    resources :categories
    resources :products do
      post :assign, on: :member
    end

    resources :stores

    get 'tags/:tag', to: 'categories#index', as: :tag

    root to: 'stores#index'

end

app/models/product.rb
class Product < ApplicationRecord
  enum allowed_size: {small: 'small', medium: 'medium', large: 'large' }
  enum allowed_color: {white: 'white', black: 'black', green: 'green', red: 'red' }

  has_many :store_products
  has_many :stores, through: :store_products
  belongs_to :category

  before_destroy :check_for_assignments, prepend: true
  
  validates :name, :color, :size, :price, presence: true
  validates :size,  inclusion: { in: allowed_sizes.keys, message: "%{value} is not a valid size." }
  validates :color, inclusion: { in: allowed_colors.keys, message: "%{value} is not a valid color." }
  validates :price, format: { with: /\A\d+(?:\.?\d*)?\z/ }, numericality: { greater_than: 0, less_than: 1000 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :category, presence: true


private

  def check_for_assignments
    if stores.any?
      errors[:base] << "cannot delete submission that has already been paid"
      throw :abort      
    end    
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :assign]
  before_action :get_stock_by_store, only: [:assign, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page],per_page: 10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end

  def assign
    break_save = false
    stores = product_params[:store]
    respond_to do |format|
      #For each stores I try to create a detail.
      stores.each do |detail|
        store = StoreProduct.where(store_id: detail.dig(:did), product_id: detail.dig(:product_id)).first_or_initialize
        store.stock = detail.dig(:stock)
        @product.stock = @product.stock - store.stock
        if !store.save
          @store_product = store 
          format.html { render :show}
        end
      end
      flash[:success]=t('.success')
      format.html { redirect_to product_url(@product) }
    end
    
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all    
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @categories = Category.all    
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: t('.success',name: @product.name) }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice:  t('.success',name: @product.name) }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    product= @product.name
    message = :success
    respond_to do |format|
      if @product.destroy
        message = t('.success', name: product)
      else
        message = t(:error_on_destroy, name: product)
      end
      format.html { redirect_to products_url, notice: message  }
      format.json { head :no_content }          
    end

  end

  private

  def get_stock_by_store
    @stores = Store.joins('LEFT OUTER JOIN store_products ON store_products.store_id = stores.id and product_id=' + @product.id.to_s)
                .select("stores.name, stores.id, store_products.stock")
    @available_units = (@product.stock>0)?(@product.stock - @stores.sum("stock")):0
    @store_product = StoreProduct.new    
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :color, :size, :price,:category_id, :stock, :store => [
                                         :did, :product_id, :stock
                                      ])
    end
    def detail_params
      params.require(:detail).permit(:id,
        store: [:store_id, :product_id, :stock])
    end    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_errors.html.erb
<% if modelo.errors.any? %>
    <div id="error_explanation">
	<h2><%= t(:errors) %> :</h2>

	<ul>
	    <% modelo.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	    <% end %>
	</ul>
    </div>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
    <%=render 'general/errors', modelo: product%>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name , class: 'form-control', maxlength: 50, autofocus: true%>
  </div>

  <div class="field">
      <%= form.label :color %>

      <%= form.select :color, options_for_select(Product.allowed_colors.map {|k, v| [t('colors.'+k.to_s).capitalize, v]},product.color) , {include_blank: true} , {class:'form-control '} %>
      
  </div>

  <div class="field">
      <%= form.label :size %>
      <%= form.select :size,options_for_select(Product.allowed_sizes.map {|k, v| [t('sizes.'+k.to_s).capitalize, v]}, product.size), {include_blank: true}, {class:'form-control select'} %>
  </div>

  <div class="field form-group">
      <%= form.label :stock %>
      <%= form.text_field :stock , class: 'form-control numberText', maxlength: 5%>
  </div>

  <div class="field form-group">
      <%= form.label :category_id %>
      <%= text_field_tag :q, ((product.category.nil?)?'':product.category.name), autocomplete: :off, class: "form-control search-input", placeholder: t(:type_your_keyword) %>  
      <%=form.hidden_field :category_id%>
      <%# form.collection_select :category_id, @categories,:id,:name, {include_blank: true}, {class: 'form-control'} %>      
  </div>
  
  
  <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, class: 'form-control allow_decimal', maxlength: 6 %>
  </div>
  
  <div class="actions">
    <%= form.submit t('.save'), :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_no_data.html.erb
<tr class="row-line row-store">
    <td colspan="8">
	<div class="no-data">
	    <%= t '.no_data'%>
	</div>
    </td>
</tr>

app/views/products/_stores.html.erb
<%= form_with(model: @store_product, url: assign_product_url(product), method: :post, local: true) do |form| %>
    <% if @store_product.errors.any? %>
	<div id="error_explanation">
	    <h2><%= pluralize(@store_product.errors.count, "error") %> prohibited this store from being saved:</h2>

	    <ul>
		<% @store_product.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		<% end %>
	    </ul>
	</div>
    <% end %>


    <div class="alert alert-success" >
    <%=t(:available_units,units: @available_units) %>
</div>
<div class="table-responsive">
    <table class="table table-hover">
	<thead>
	    <tr>
		<th><%=t 'activerecord.attributes.store.name'%></th>
		<th><%=t 'activerecord.attributes.product.stock'%></th>
		<th></th>

		<th colspan="2"></th>
	    </tr>
	</thead>

	<tbody>
	    <%if !@stores.nil?%>
		<% @stores.each do |store| %>
		    <tr class="row-line row-store">
			<td><%= store.name %></td>
			<%=hidden_field_tag 'product[store][][did]', store.id %>			
			<%=hidden_field_tag 'product[store][][product_id]', @product.id %>
			<td><%= text_field_tag "product[store][][stock]",  store.stock||0, class:'form-control numberText', size:1, maxlength: 4%></td>
			<td>

			</td>
		    </tr>
		<%end%>
   		<%if @stores.length==0%>
		    <%=render 'stores/no_data' %>
		<% end %>
	    <%else%>
		<%=render 'stores/no_data' %>
	    <%end%>
	</tbody>
	<tr>
	    <td></td>

	    <td>
		<%=form.submit t('.save'), class: 'btn btn-danger text-center' %>
	    </td>
	    <td></td>	    
	</tr>
    </table>

    </div>
<%end%>   

app/views/products/_tabs.html.erb
<h1><%=t('.title',name: product.name) %></h1>
<div class="container">
    <ul class="nav nav-pills">
	<li role="presentation" class="<%=isActionActive("edit") %>"><%=link_to t(:general), edit_product_path(product), class: 'submnu mnu-general' %></li>
	<li role="presentation" class="<%=isActionActive("assign")%><%=isActionActive("show")%>"><%=link_to t(:assign_stores), product, class: 'submnu mnu-assign',id:'mnuassign' %></li>
</ul>
</div>

app/views/products/edit.html.erb
<div class="card">
    <%= render 'tabs', product: @product %>
    <%= render 'form', product: @product %>
</div>
<%= link_to (:back), products_path %>

app/views/products/index.html.erb
<div class="card">
    <h1><%= t '.title' %></h1>
    <p>
	<%= link_to t('new'), new_product_path, class: 'btn btn-primary' %>
    </p>
    <div class="table-responsive">
	<table class="table table-hover">
	    <thead>
		<tr>
		    <th><%=t('activerecord.attributes.product.name') %></th>
		    <th><%=t('activerecord.attributes.product.color')%></th>
		    <th><%=t('activerecord.attributes.product.size')%></th>
		    <th><%=t('activerecord.attributes.product.price')%></th>
		    <th><%=t('activerecord.attributes.product.stock')%></th>		    
		    <th colspan="3"></th>
		</tr>
	    </thead>

	    <tbody>
		<%if !@products.nil?%>		
		    <% @products.each do |product| %>
			<tr class="row-line row-product">
			    <td><%= link_to product.name, edit_product_path(product) %></td>
			    <td><%= t('colors.' + product.color).capitalize %></td>
			    <td><%= t('sizes.' + product.size).capitalize %></td>
			    <td><%= product.price %></td>
			    <td><%= product.stock %></td>			    
			    <td><%= link_to t(:edit), edit_product_path(product) %></td>
			    <td><%= link_to t(:destroy), product, method: :delete, data: { confirm: t(:are_you_sure, name: product.name) } %></td>
			</tr>
		    <% end %>
		    <%if @products.length==0%>
			<%=render 'stores/no_data' %>
		    <% end %>		    
		<%else%>
		    <%=render 'stores/no_data' %>
		<% end %>		    
	    </tbody>
	</table>
	<%= will_paginate @products %>
    </div>
</div>
<br>

app/views/products/new.html.erb
<div class="card">
    <h1><%= t( '.title',name: @product.name) %></h1>
    <%= render 'form', product: @product %>
</div>

<%= link_to t(:back), products_path %>

app/views/products/show.html.erb
<div class="card">
    <%= render 'tabs', product: @product %>
    <%= render 'stores', product: @product %>
</div>
<%= link_to (:back), products_path %>